apiVersion: v1
kind: Service
metadata:
  name: tomcat-service
spec:
  type: NodePort  # Change to LoadBalancer for cloud environments
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30000  # Optional: specify a port to access Tomcat
  selector:
    app: tomcat
